# site settings
title: Keren Braids
subtitle: by Keren Styling
email: amram.k@gmail.com
description: I love doing braids and I can help you with it!<br /> for any beauty and styling dont hesitate just contact me!
baseurl: "/keren-braids-forty" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Hatoren 8/19
city: Yavne
state: Israel
zip_code: 810483
country: Israel
phone: (+972) 50-901-1255 (050-9011255)

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
